# Generated by Django 6.0.5 on 2026-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.CharField(choices=[('array', 'Array'), ('string', 'String'), ('linked_list', 'Linked List'), ('stack_queue', 'Stack & Queue'), ('trees', 'Trees'), ('graphs', 'Graphs'), ('heap', 'Heap'), ('dp', 'DP'), ('greedy', 'Greedy'), ('backtracking', 'Backtracking'), ('binary_search', 'Binary Search'), ('two_pointers', 'Two Pointers'), ('sliding_window', 'Sliding Window'), ('bit_manipulation', 'Bit Manipulation'), ('math', 'Math')], max_length=20),
        ),
    ]
