# Generated by Django 6.0.5 on 2026-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_started_at_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
