# Generated by Django 6.0.5 on 2026-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('time_limit_exceeded', 'Time Limit Exceeded')], max_length=20),
        ),
    ]
