# Generated by Django 6.0.5 on 2026-06-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
