# Generated by Django 6.0.5 on 2026-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='failure_detail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
