from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds User.has_set_username.

    Additive only - the autogenerated version also wanted to narrow User.id
    from BigAutoField to AutoField, the same pre-existing DEFAULT_AUTO_FIELD
    drift left out of every other migration here.

    The RunSQL step matters more than it looks. Django adds a column with a
    default and then immediately drops it, treating defaults as an application
    concern. This project migrates a hosted database that the deployed release
    also uses, so there is always a window where the running code predates the
    column: during it, every INSERT of a user omits this column and fails the
    NOT NULL constraint. Keeping the default in the database closes that
    window - and skipping it is exactly what took room creation down twice.
    """

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_username',
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE users_user ALTER COLUMN has_set_username SET DEFAULT true;",
            reverse_sql="ALTER TABLE users_user ALTER COLUMN has_set_username DROP DEFAULT;",
        ),
    ]
